### PR TITLE
Update status_codes.json

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
some cool rewrite

### CODE REVIEW

**Comment by malmeloo** [comment]
I don't really think the "is"es in front make much sense, as it's already in a status field

**Comment by yeah-its-gloria** [comment]
oh, wait i remove that "Is"

**Comment by malmeloo** [comment]
Oh and btw, the "friend game" => "friend room" is already planned for the next update, but I could add the :/ at the end of status 4 lol

**Comment by malmeloo** [comment]
I'll add the ":/" to status 4 in the next update, but keep the current statuses. Closing this PR for now.

**Comment by yeah-its-gloria** [comment]
Okay, i will make some research on the status code 4

**Pull request closed without merging**
