### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yeah-its-gloria**

### CODE REVIEW

**Comment by yeah-its-gloria** [comment]
some cool additions

**Comment by yeah-its-gloria** [comment]
you need to correct the releases url, but everything other should be fine

**Comment by malmeloo** [comment]
Thanks, but I'm not gonna merge that wiimmfi game ID section. I'll edit it when I've got a computer near.

**Comment by malmeloo** [comment]
thanks :ok_hand:

**Pull request merged**
